#!/usr/bin/env ruby

require "time"
require "date"
require "shellwords"
require "fileutils"

## Development tasks
#
# 1. Use the proper team names in the MP3 tags.
# 2. Convert the pub time to the time zone the game was played in.

## Constants

hosted_dir = "/webapps/downloads/alexcast"

## Parse user input

requested_date = Date.parse(ARGV.shift)
requested_team = ARGV.shift
requested_iteration = ARGV.shift

## Get the MLB listing

listing = `python mlblistings.py startdate=#{ requested_date.strftime '%m/%d/%y' }`

if $?.exitstatus != 0
  puts "could not load mlb listing for #{ requested_date }"
  exit 1
end

puts listing
puts

## Find the requested game

games = listing.scan(%r{\w:\s*(\d+:\d+ \w+): (\d{4})/(\d{2})/(\d{2})/([a-z]{3})mlb-([a-z]{3})mlb-(\d+) E: (.*)})

game =
  games.find do |time, year, month, day, away_team, home_team, iteration, event_id|
    ((home_team == requested_team) || (away_team == requested_team)) && (iteration == requested_iteration)
  end

if game == nil
  puts "could not find a game for #{ requested_team } at iteration #{ requested_iteration }"
  exit 2
end

(time, year, month, day, away_team, home_team, iteration, event_id) = game

## Print game details

puts "Game starts at : #{ time }"
puts "Game matchup   : #{ away_team.upcase } at #{ home_team.upcase }"
puts "Event ID       : #{ event_id }"
puts

## Download the game, encode it to mp3

j   = [ month, day, year[/\d\d$/] ].join("/")
e   = event_id
a   = requested_team
mp3 = [ a, year + month + day, iteration, "mp3" ].join(".")

system "rm -f mlbgame.wav"
system "python mlbplay.py j=#{ j } e=#{ e } a=#{ a }" or raise "couldn't finish download"
system "lame -a mlbgame.wav #{ Shellwords.escape(mp3) }" or raise "couldn't encode mp3"

## Set mp3 tags

title = "#{ away_team.upcase } at #{ home_team.upcase } - #{ month }/#{ day }/#{ year }-#{ iteration }"

system "id3v2 --TIT2 #{ Shellwords.escape(title) } #{ Shellwords.escape(mp3) }"
system "id3v2 --TPE1 #{ Shellwords.escape('Radio Broadcast') } #{ Shellwords.escape(mp3) }"
system "touch -d '#{ year }-#{ month }-#{ day } #{ time }' #{ Shellwords.escape(mp3) }"

## Deploy the new file

FileUtils.rm_rf "mlbgame.wav"
FileUtils.mv mp3, hosted_dir
system File.join(hosted_dir, "render.sh")
