source 'https://rubygems.org'

gem 'awesome_print', require: 'ap'
gem 'thor'
gem 'terminal-table'
gem 'chronic'
gem 'activesupport', require: 'active_support/time'
gem 'term-ansicolor', require: 'term/ansicolor'
gem 'typhoeus'
gem 'highline', require: 'highline/import'
gem 'sinatra', require: false
gem 'slim'
gem 'compass'
gem 'sass'
gem 'coffee-script'
